<style>
    .printlabels-top-container {
      display: flex;
        flex-wrap: wrap;
    }
    .printlabels-top-container > div {
        flex: 0 1 auto;
        width: 100%;
    }
    .pager-bar {
        margin:     1.5rem 0;
        text-align: center;
    }

    .pager-bar ul {
        margin: 0 auto;
    }
    

    .info-bar {
        padding: 1.5rem 0;
    }

    .action-button {
        background-color: #eb5202;
        border-color:     #eb5202;
        color:            #ffffff;
        text-shadow:      1px 1px 0 rgba(0, 0, 0, 0.25);
        border:           1px solid;
        border-radius:    0;
        display:          inline-block;
        font-family:      'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif;
        font-size:        1.4rem;
        font-weight:      600;
        line-height:      1.36;
        padding:          0.6rem 1em 0.6rem;
        text-align:       center;
        vertical-align:   baseline;
        cursor:           pointer;
    }

    .action-button:hover {
        background-color: #ba4000;
        border-color:     #b84002;
        box-shadow:       0 0 0 1px #007bdb;
        color:            #ffffff;
        text-decoration:  none;
    }

    .actions-toolbar {
        padding-top: 20px;
    }

    .actions-toolbar > row {
        align-items: center;
    }

    .success-message {
        background-color: #79a22e;
    }

    .error-message {
        background-color: #ee7d7d;
    }

    .excluded td {
        background-color: #ee7d7d !important;
    }

    .included td {
        background-color: #79a22e !important;
    }

    #order_data_hidden {
        display: none;
    }

    .problem-order-desc {
        margin-bottom: 15px;
    }

    .order-details-top {
        margin-bottom: 20px;
    }

    .order-items {
    }

    .order-item-shrt {
        margin-bottom: 5px;
    }

    .order-item-shrt-child {
        padding-left: 5px;
        padding-top:  5px;
    }

    .addresses-output {
        display: flex;
    }

    .addresses-output > div {
        flex:  0 1 auto;
        width: 50%;
    }

    .addresses-output > div:first-child {
        margin-right: 20px;
    }

    .addresses-output > div:last-child {
        margin-left: 20px;
    }

    .addresses-output .panel-heading {
        text-transform: capitalize;
    }

    .addresses-output .field-title {
        font-weight: 700;
    }

    .order-data-section {
        margin-bottom: 10px;
        display:       flex;
    }

    .order-data-section .field-title {
        margin-right: 5px;
    }

    .order-data-section > div {
        flex: 0 1 auto;
    }

    .order-data-section .field-title {
        font-weight: 700;
    }

    .field-title {
        font-weight: 700;
    }

    .order-item-shrt {
        width: 100%;
        clear: both;
    }

    @media only screen and (min-width: 992px) {
        .orders-ship-tb-items {
            min-width: 300px;
        }
    }

    .loader {
        border:        16px solid #f3f3f3; /* Light grey */
        border-top:    16px solid #3498db; /* Blue */
        border-radius: 50%;
        width:         120px;
        height:        120px;
        animation:     spin 2s linear infinite;
        margin:        0 auto;
    }

    @keyframes spin {
        0% {
            transform: rotate(0deg);
        }
        100% {
            transform: rotate(360deg);
        }
    }

    .loading {
        position: fixed;
        z-index:  999;
        height:   2em;
        width:    100%;
        overflow: visible;
        margin:   auto;
        top:      0;
        left:     0;
        bottom:   0;
        right:    0;
        display:  none;
    }

    .loading:before {
        content:          '';
        display:          block;
        position:         fixed;
        top:              0;
        left:             0;
        width:            100%;
        height:           100%;
        background-color: rgba(0, 0, 0, 0.7);
    }

    .loader-message {

        margin-top: 20px;
        color:      #f3f3f3;
        width:      100%;
        margin:     0 auto;
        text-align: center;
        /* z-index: 99999990; */
        font-size:  30px;
        /* background: white; */
        z-index:    1;
        position:   relative;
    }


    .btn {
        display:          inline-block;
        font-weight:      400;
        color:            #333;
        text-align:       center;
        vertical-align:   middle;
        cursor:           pointer;
        user-select:      none;
        background-color: transparent;
        border:           1px solid transparent;
        padding:          0.375rem 0.75rem;
        font-size:        1.25rem;
        line-height:      1.5;
        border-radius:    0;
        transition:       color 0.15s ease-in-out, background-color 0.15s ease-in-out, border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
    }

    @media (prefers-reduced-motion: reduce) {
        .btn {
            transition: none;
        }
    }

    .btn:hover {
        color:           #333;
        text-decoration: none;
    }

    .btn:focus, .btn.focus, .focus.action:not(.link-action) {
        outline: 0;
    }

    .btn.disabled, .btn:disabled, .action:not(.link-action):disabled {
        opacity: 0.65;
    }

    a.btn.disabled, a.disabled.action:not(.link-action), fieldset:disabled a.btn, fieldset:disabled a.action:not(.link-action) {
        pointer-events: none;
    }

    .btn-primary {
        color: #fff;
        background-color: #007bff;
        border-color: #007bff;
    }
    .btn-primary:hover {
        color: #fff;
        background-color: #0069d9;
        border-color: #0062cc;
    }
    .btn-primary:focus, .btn-primary.focus {
        color: #fff;
        background-color: #0069d9;
        border-color: #0062cc;
    }
    .btn-primary.disabled, .btn-primary:disabled {
        color: #fff;
        background-color: #007bff;
        border-color: #007bff;
    }
    .btn-primary:not(:disabled):not(.disabled):active, .btn-primary:not(:disabled):not(.disabled).active, .show > .btn-primary.dropdown-toggle {
        color: #fff;
        background-color: #0062cc;
        border-color: #005cbf;
    }
    .btn-secondary {
        color: #fff;
        background-color: #6c757d;
        border-color: #6c757d;
    }
    .btn-secondary:hover {
        color: #fff;
        background-color: #5a6268;
        border-color: #545b62;
    }
    .btn-secondary:focus, .btn-secondary.focus {
        color: #fff;
        background-color: #5a6268;
        border-color: #545b62;
    }
    .btn-secondary.disabled, .btn-secondary:disabled {
        color: #fff;
        background-color: #6c757d;
        border-color: #6c757d;
    }
    .btn-secondary:not(:disabled):not(.disabled):active, .btn-secondary:not(:disabled):not(.disabled).active, .show > .btn-secondary.dropdown-toggle {
        color: #fff;
        background-color: #545b62;
        border-color: #4e555b;
    }
    .btn-success {
        color: #fff;
        background-color: #28a745;
        border-color: #28a745;
    }
    .btn-success:hover {
        color: #fff;
        background-color: #218838;
        border-color: #1e7e34;
    }
    .btn-success:focus, .btn-success.focus {
        color: #fff;
        background-color: #218838;
        border-color: #1e7e34;
    }
    .btn-success.disabled, .btn-success:disabled {
        color: #fff;
        background-color: #28a745;
        border-color: #28a745;
    }
    .btn-success:not(:disabled):not(.disabled):active, .btn-success:not(:disabled):not(.disabled).active, .show > .btn-success.dropdown-toggle {
        color: #fff;
        background-color: #1e7e34;
        border-color: #1c7430;
    }
    .btn-info {
        color: #fff;
        background-color: #17a2b8;
        border-color: #17a2b8;
    }
    .btn-info:hover {
        color: #fff;
        background-color: #138496;
        border-color: #117a8b;
    }
    .btn-info:focus, .btn-info.focus {
        color: #fff;
        background-color: #138496;
        border-color: #117a8b;
    }
    .btn-info.disabled, .btn-info:disabled {
        color: #fff;
        background-color: #17a2b8;
        border-color: #17a2b8;
    }
    .btn-info:not(:disabled):not(.disabled):active, .btn-info:not(:disabled):not(.disabled).active, .show > .btn-info.dropdown-toggle {
        color: #fff;
        background-color: #117a8b;
        border-color: #10707f;
    }
    .btn-warning {
        color: #212529;
        background-color: #ffc107;
        border-color: #ffc107;
    }
    .btn-warning:hover {
        color: #212529;
        background-color: #e0a800;
        border-color: #d39e00;
    }
    .btn-warning:focus, .btn-warning.focus {
        color: #212529;
        background-color: #e0a800;
        border-color: #d39e00;
    }
    .btn-warning.disabled, .btn-warning:disabled {
        color: #212529;
        background-color: #ffc107;
        border-color: #ffc107;
    }
    .btn-warning:not(:disabled):not(.disabled):active, .btn-warning:not(:disabled):not(.disabled).active, .show > .btn-warning.dropdown-toggle {
        color: #212529;
        background-color: #d39e00;
        border-color: #c69500;
    }
    .btn-danger {
        color: #fff;
        background-color: #dc3545;
        border-color: #dc3545;
    }
    .btn-danger:hover {
        color: #fff;
        background-color: #c82333;
        border-color: #bd2130;
    }
    .btn-danger:focus, .btn-danger.focus {
        color: #fff;
        background-color: #c82333;
        border-color: #bd2130;
    }
    .btn-danger.disabled, .btn-danger:disabled {
        color: #fff;
        background-color: #dc3545;
        border-color: #dc3545;
    }
    .btn-danger:not(:disabled):not(.disabled):active, .btn-danger:not(:disabled):not(.disabled).active, .show > .btn-danger.dropdown-toggle {
        color: #fff;
        background-color: #bd2130;
        border-color: #b21f2d;
    }
    .btn-light {
        color: #212529;
        background-color: #f8f9fa;
        border-color: #f8f9fa;
    }
    .btn-light:hover {
        color: #212529;
        background-color: #e2e6ea;
        border-color: #dae0e5;
    }
    .btn-light:focus, .btn-light.focus {
        color: #212529;
        background-color: #e2e6ea;
        border-color: #dae0e5;
    }
    .btn-light.disabled, .btn-light:disabled {
        color: #212529;
        background-color: #f8f9fa;
        border-color: #f8f9fa;
    }
    .btn-light:not(:disabled):not(.disabled):active, .btn-light:not(:disabled):not(.disabled).active, .show > .btn-light.dropdown-toggle {
        color: #212529;
        background-color: #dae0e5;
        border-color: #d3d9df;
    }
    .btn-dark {
        color: #fff;
        background-color: #343a40;
        border-color: #343a40;
    }
    .btn-dark:hover {
        color: #fff;
        background-color: #23272b;
        border-color: #1d2124;
    }
    .btn-dark:focus, .btn-dark.focus {
        color: #fff;
        background-color: #23272b;
        border-color: #1d2124;
    }
    .btn-dark.disabled, .btn-dark:disabled {
        color: #fff;
        background-color: #343a40;
        border-color: #343a40;
    }
    .btn-dark:not(:disabled):not(.disabled):active, .btn-dark:not(:disabled):not(.disabled).active, .show > .btn-dark.dropdown-toggle {
        color: #fff;
        background-color: #1d2124;
        border-color: #171a1d;
    }
    .btn-outline-primary {
        color: #007bff;
        border-color: #007bff;
    }
    .btn-outline-primary:hover {
        color: #fff;
        background-color: #007bff;
        border-color: #007bff;
    }
    .btn-outline-primary:focus, .btn-outline-primary.focus {
        box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, 0.5);
    }
    .btn-outline-primary.disabled, .btn-outline-primary:disabled {
        color: #007bff;
        background-color: transparent;
    }
    .btn-outline-primary:not(:disabled):not(.disabled):active, .btn-outline-primary:not(:disabled):not(.disabled).active, .show > .btn-outline-primary.dropdown-toggle {
        color: #fff;
        background-color: #007bff;
        border-color: #007bff;
    }
    .btn-outline-primary:not(:disabled):not(.disabled):active:focus, .btn-outline-primary:not(:disabled):not(.disabled).active:focus, .show > .btn-outline-primary.dropdown-toggle:focus {
        box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, 0.5);
    }
    .btn-outline-secondary {
        color: #6c757d;
        border-color: #6c757d;
    }
    .btn-outline-secondary:hover {
        color: #fff;
        background-color: #6c757d;
        border-color: #6c757d;
    }
    .btn-outline-secondary:focus, .btn-outline-secondary.focus {
        box-shadow: 0 0 0 0.2rem rgba(108, 117, 125, 0.5);
    }
    .btn-outline-secondary.disabled, .btn-outline-secondary:disabled {
        color: #6c757d;
        background-color: transparent;
    }
    .btn-outline-secondary:not(:disabled):not(.disabled):active, .btn-outline-secondary:not(:disabled):not(.disabled).active, .show > .btn-outline-secondary.dropdown-toggle {
        color: #fff;
        background-color: #6c757d;
        border-color: #6c757d;
    }
    .btn-outline-secondary:not(:disabled):not(.disabled):active:focus, .btn-outline-secondary:not(:disabled):not(.disabled).active:focus, .show > .btn-outline-secondary.dropdown-toggle:focus {
        box-shadow: 0 0 0 0.2rem rgba(108, 117, 125, 0.5);
    }
    .btn-outline-success {
        color: #28a745;
        border-color: #28a745;
    }
    .btn-outline-success:hover {
        color: #fff;
        background-color: #28a745;
        border-color: #28a745;
    }
    .btn-outline-success:focus, .btn-outline-success.focus {
        box-shadow: 0 0 0 0.2rem rgba(40, 167, 69, 0.5);
    }
    .btn-outline-success.disabled, .btn-outline-success:disabled {
        color: #28a745;
        background-color: transparent;
    }
    .btn-outline-success:not(:disabled):not(.disabled):active, .btn-outline-success:not(:disabled):not(.disabled).active, .show > .btn-outline-success.dropdown-toggle {
        color: #fff;
        background-color: #28a745;
        border-color: #28a745;
    }
    .btn-outline-success:not(:disabled):not(.disabled):active:focus, .btn-outline-success:not(:disabled):not(.disabled).active:focus, .show > .btn-outline-success.dropdown-toggle:focus {
        box-shadow: 0 0 0 0.2rem rgba(40, 167, 69, 0.5);
    }
    .btn-outline-info {
        color: #17a2b8;
        border-color: #17a2b8;
    }
    .btn-outline-info:hover {
        color: #fff;
        background-color: #17a2b8;
        border-color: #17a2b8;
    }
    .btn-outline-info:focus, .btn-outline-info.focus {
        box-shadow: 0 0 0 0.2rem rgba(23, 162, 184, 0.5);
    }
    .btn-outline-info.disabled, .btn-outline-info:disabled {
        color: #17a2b8;
        background-color: transparent;
    }
    .btn-outline-info:not(:disabled):not(.disabled):active, .btn-outline-info:not(:disabled):not(.disabled).active, .show > .btn-outline-info.dropdown-toggle {
        color: #fff;
        background-color: #17a2b8;
        border-color: #17a2b8;
    }
    .btn-outline-info:not(:disabled):not(.disabled):active:focus, .btn-outline-info:not(:disabled):not(.disabled).active:focus, .show > .btn-outline-info.dropdown-toggle:focus {
        box-shadow: 0 0 0 0.2rem rgba(23, 162, 184, 0.5);
    }
    .btn-outline-warning {
        color: #ffc107;
        border-color: #ffc107;
    }
    .btn-outline-warning:hover {
        color: #212529;
        background-color: #ffc107;
        border-color: #ffc107;
    }
    .btn-outline-warning:focus, .btn-outline-warning.focus {
        box-shadow: 0 0 0 0.2rem rgba(255, 193, 7, 0.5);
    }
    .btn-outline-warning.disabled, .btn-outline-warning:disabled {
        color: #ffc107;
        background-color: transparent;
    }
    .btn-outline-warning:not(:disabled):not(.disabled):active, .btn-outline-warning:not(:disabled):not(.disabled).active, .show > .btn-outline-warning.dropdown-toggle {
        color: #212529;
        background-color: #ffc107;
        border-color: #ffc107;
    }
    .btn-outline-warning:not(:disabled):not(.disabled):active:focus, .btn-outline-warning:not(:disabled):not(.disabled).active:focus, .show > .btn-outline-warning.dropdown-toggle:focus {
        box-shadow: 0 0 0 0.2rem rgba(255, 193, 7, 0.5);
    }
    .btn-outline-danger {
        color: #dc3545;
        border-color: #dc3545;
    }
    .btn-outline-danger:hover {
        color: #fff;
        background-color: #dc3545;
        border-color: #dc3545;
    }
    .btn-outline-danger:focus, .btn-outline-danger.focus {
        box-shadow: 0 0 0 0.2rem rgba(220, 53, 69, 0.5);
    }
    .btn-outline-danger.disabled, .btn-outline-danger:disabled {
        color: #dc3545;
        background-color: transparent;
    }
    .btn-outline-danger:not(:disabled):not(.disabled):active, .btn-outline-danger:not(:disabled):not(.disabled).active, .show > .btn-outline-danger.dropdown-toggle {
        color: #fff;
        background-color: #dc3545;
        border-color: #dc3545;
    }
    .btn-outline-danger:not(:disabled):not(.disabled):active:focus, .btn-outline-danger:not(:disabled):not(.disabled).active:focus, .show > .btn-outline-danger.dropdown-toggle:focus {
        box-shadow: 0 0 0 0.2rem rgba(220, 53, 69, 0.5);
    }
    .btn-outline-light {
        color: #f8f9fa;
        border-color: #f8f9fa;
    }
    .btn-outline-light:hover {
        color: #212529;
        background-color: #f8f9fa;
        border-color: #f8f9fa;
    }
    .btn-outline-light:focus, .btn-outline-light.focus {
        box-shadow: 0 0 0 0.2rem rgba(248, 249, 250, 0.5);
    }
    .btn-outline-light.disabled, .btn-outline-light:disabled {
        color: #f8f9fa;
        background-color: transparent;
    }
    .btn-outline-light:not(:disabled):not(.disabled):active, .btn-outline-light:not(:disabled):not(.disabled).active, .show > .btn-outline-light.dropdown-toggle {
        color: #212529;
        background-color: #f8f9fa;
        border-color: #f8f9fa;
    }
    .btn-outline-light:not(:disabled):not(.disabled):active:focus, .btn-outline-light:not(:disabled):not(.disabled).active:focus, .show > .btn-outline-light.dropdown-toggle:focus {
        box-shadow: 0 0 0 0.2rem rgba(248, 249, 250, 0.5);
    }
    .btn-outline-dark {
        color: #343a40;
        border-color: #343a40;
    }
    .btn-outline-dark:hover {
        color: #fff;
        background-color: #343a40;
        border-color: #343a40;
    }
    .btn-outline-dark:focus, .btn-outline-dark.focus {
        box-shadow: 0 0 0 0.2rem rgba(52, 58, 64, 0.5);
    }
    .btn-outline-dark.disabled, .btn-outline-dark:disabled {
        color: #343a40;
        background-color: transparent;
    }
    .btn-outline-dark:not(:disabled):not(.disabled):active, .btn-outline-dark:not(:disabled):not(.disabled).active, .show > .btn-outline-dark.dropdown-toggle {
        color: #fff;
        background-color: #343a40;
        border-color: #343a40;
    }
    .btn-outline-dark:not(:disabled):not(.disabled):active:focus, .btn-outline-dark:not(:disabled):not(.disabled).active:focus, .show > .btn-outline-dark.dropdown-toggle:focus {
        box-shadow: 0 0 0 0.2rem rgba(52, 58, 64, 0.5);
    }
    .btn-link {
        font-weight: 400;
        color: #302624;
        text-decoration: none;
    }
    .btn-link:hover {
        color: #040303;
        text-decoration: underline;
    }
    .btn-link:focus, .btn-link.focus {
        text-decoration: underline;
        box-shadow: none;
    }
    .btn-link:disabled, .btn-link.disabled {
        color: #6c757d;
        pointer-events: none;
    }
    .btn-lg {
        padding: 0.5rem 1rem;
        font-size: calc(1.025rem + 0.3vw);
        line-height: 1.5;
        border-radius: 0;
    }
    @media (min-width: 1200px) {
        .btn-lg {
            font-size: 1.25rem;
        }
    }
    .btn-sm {
        padding: 0.25rem 0.5rem;
        font-size: 0.875rem;
        line-height: 1.5;
        border-radius: 0;
    }
    .btn-block {
        display: block;
        width: 100%;
    }
    .btn-block + .btn-block {
        margin-top: 0.5rem;
    }
    input[type="submit"].btn-block, input[type="reset"].btn-block, input[type="button"].btn-block {
        width: 100%;
    }



    .badge {
        display:        inline-block;
        padding:        0.25em 0.4em;
        font-weight:    700;
        line-height:    1;
        text-align:     center;
        white-space:    nowrap;
        vertical-align: baseline;
        transition:     color 0.15s ease-in-out, background-color 0.15s ease-in-out, border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
    }

    @media (prefers-reduced-motion: reduce) {
        .badge {
            transition: none;
        }
    }

    a.badge:hover, a.badge:focus {
        text-decoration: none;
    }

    .badge:empty {
        display: none;
    }

    .btn .badge, .action:not(.link-action) .badge {
        position: relative;
        top:      -1px;
    }

    .badge-pill {
        padding-right: 0.6em;
        padding-left:  0.6em;
    }

    .badge-primary {
        color:            #fff;
        background-color: #007bff;
    }

    a.badge-primary:hover, a.badge-primary:focus {
        color:            #fff;
        background-color: #0062cc;
    }

    a.badge-primary:focus, a.badge-primary.focus {
        outline:    0;
        box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, 0.5);
    }

    .badge-secondary {
        color:            #fff;
        background-color: #6c757d;
    }

    a.badge-secondary:hover, a.badge-secondary:focus {
        color:            #fff;
        background-color: #545b62;
    }

    a.badge-secondary:focus, a.badge-secondary.focus {
        outline:    0;
        box-shadow: 0 0 0 0.2rem rgba(108, 117, 125, 0.5);
    }

    .badge-success {
        color:            #fff;
        background-color: #28a745;
    }

    a.badge-success:hover, a.badge-success:focus {
        color:            #fff;
        background-color: #1e7e34;
    }

    a.badge-success:focus, a.badge-success.focus {
        outline:    0;
        box-shadow: 0 0 0 0.2rem rgba(40, 167, 69, 0.5);
    }

    .badge-info {
        color:            #fff;
        background-color: #17a2b8;
    }

    a.badge-info:hover, a.badge-info:focus {
        color:            #fff;
        background-color: #117a8b;
    }

    a.badge-info:focus, a.badge-info.focus {
        outline:    0;
        box-shadow: 0 0 0 0.2rem rgba(23, 162, 184, 0.5);
    }

    .badge-warning {
        color:            #212529;
        background-color: #ffc107;
    }

    a.badge-warning:hover, a.badge-warning:focus {
        color:            #212529;
        background-color: #d39e00;
    }

    a.badge-warning:focus, a.badge-warning.focus {
        outline:    0;
        box-shadow: 0 0 0 0.2rem rgba(255, 193, 7, 0.5);
    }

    .badge-danger {
        color:            #fff;
        background-color: #dc3545;
    }

    a.badge-danger:hover, a.badge-danger:focus {
        color:            #fff;
        background-color: #bd2130;
    }

    a.badge-danger:focus, a.badge-danger.focus {
        outline:    0;
        box-shadow: 0 0 0 0.2rem rgba(220, 53, 69, 0.5);
    }

    .badge-light {
        color:            #212529;
        background-color: #f8f9fa;
    }

    a.badge-light:hover, a.badge-light:focus {
        color:            #212529;
        background-color: #dae0e5;
    }

    a.badge-light:focus, a.badge-light.focus {
        outline:    0;
        box-shadow: 0 0 0 0.2rem rgba(248, 249, 250, 0.5);
    }

    .badge-dark {
        color:            #fff;
        background-color: #343a40;
    }

    a.badge-dark:hover, a.badge-dark:focus {
        color:            #fff;
        background-color: #1d2124;
    }

    a.badge-dark:focus, a.badge-dark.focus {
        outline:    0;
        box-shadow: 0 0 0 0.2rem rgba(52, 58, 64, 0.5);
    }

    .pagination {
        display:       -ms-flexbox;
        display:       flex;
        padding-left:  0;
        list-style:    none;
        border-radius: .25rem
    }

    .page-link {
        position:         relative;
        display:          block;
        padding:          .5rem .75rem;
        margin-left:      -1px;
        line-height:      1.25;
        color:            #007bff;
        background-color: #fff;
        border:           1px solid #dee2e6
    }

    .page-link:hover {
        z-index:          2;
        color:            #0056b3;
        text-decoration:  none;
        background-color: #e9ecef;
        border-color:     #dee2e6
    }

    .page-link:focus {
        z-index:    3;
        outline:    0;
        box-shadow: 0 0 0 .2rem rgba(0, 123, 255, .25)
    }

    .page-item:first-child .page-link {
        margin-left:               0;
        border-top-left-radius:    .25rem;
        border-bottom-left-radius: .25rem
    }

    .page-item:last-child .page-link {
        border-top-right-radius:    .25rem;
        border-bottom-right-radius: .25rem
    }

    .page-item.active .page-link {
        z-index:          3;
        color:            #fff;
        background-color: #007bff;
        border-color:     #007bff
    }

    .page-item.disabled .page-link {
        color:            #6c757d;
        pointer-events:   none;
        cursor:           auto;
        background-color: #fff;
        border-color:     #dee2e6
    }

    .pagination-lg .page-link {
        padding:     .75rem 1.5rem;
        font-size:   1.25rem;
        line-height: 1.5
    }

    .pagination-lg .page-item:first-child .page-link {
        border-top-left-radius:    .3rem;
        border-bottom-left-radius: .3rem
    }

    .pagination-lg .page-item:last-child .page-link {
        border-top-right-radius:    .3rem;
        border-bottom-right-radius: .3rem
    }

    .pagination-sm .page-link {
        padding:     .25rem .5rem;
        font-size:   .875rem;
        line-height: 1.5
    }

    .pagination-sm .page-item:first-child .page-link {
        border-top-left-radius:    .2rem;
        border-bottom-left-radius: .2rem
    }

    .pagination-sm .page-item:last-child .page-link {
        border-top-right-radius:    .2rem;
        border-bottom-right-radius: .2rem
    }

    /* Table SOrter */
    .tablesorter-bootstrap {
        width: 100%
    }

    .tablesorter-bootstrap tfoot td, .tablesorter-bootstrap tfoot th, .tablesorter-bootstrap thead td, .tablesorter-bootstrap thead th {
        font-weight: 700;
        padding:     4px;
        margin:      0 0 18px
    }

    .tablesorter-bootstrap thead .tablesorter-header {
        background-position: right 5px center;
        background-repeat:   no-repeat;
        cursor:              pointer;
        white-space:         normal
    }

    .tablesorter-bootstrap:not(.table-dark) tfoot td, .tablesorter-bootstrap:not(.table-dark) tfoot th, .tablesorter-bootstrap:not(.table-dark) thead:not(.thead-dark) .tablesorter-header {
        background-color: #eee
    }

    .tablesorter-bootstrap thead .sorter-false {
        cursor:           default;
        background-image: none
    }

    .tablesorter-bootstrap .tablesorter-header-inner {
        position: relative;
        padding:  4px 18px 4px 4px
    }

    .tablesorter-bootstrap .sorter-false .tablesorter-header-inner {
        padding: 4px
    }

    .tablesorter-bootstrap thead .tablesorter-headerUnSorted:not(.sorter-false) {
        background-image: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMiIgaGVpZ2h0PSIxNiIgdmlld0JveD0iMCAwIDE0IDIwIj48cGF0aCBkPSJNMTQgMTNsLTIuNS0yLjVMNyAxNWwtNC41LTQuNUwwIDEzbDcgN3pNMTQgNy41TDExLjUgMTAgNyA1LjUgMi41IDEwIDAgNy41bDctN3oiLz48L3N2Zz4=)
    }

    .tablesorter-bootstrap thead .tablesorter-headerAsc {
        background-image: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMiIgaGVpZ2h0PSIxMiIgdmlld0JveD0iMCAwIDE0IDE0Ij48cGF0aCBkPSJNMTQgOS41TDExLjUgMTIgNyA3LjUgMi41IDEyIDAgOS41bDctN3oiLz48L3N2Zz4=)
    }

    .tablesorter-bootstrap thead .tablesorter-headerDesc {
        background-image: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMiIgaGVpZ2h0PSIxMiIgdmlld0JveD0iMCAwIDE0IDE0Ij48cGF0aCBkPSJNMTQgNWwtMi41LTIuNS00LjUgNC41LTQuNS00LjVMMCA1IDcgMTJ6Ii8+PC9zdmc+)
    }

    .tablesorter-bootstrap thead.thead-dark .tablesorter-headerUnSorted:not(.sorter-false), .tablesorter-bootstrap.table-dark thead .tablesorter-headerUnSorted:not(.sorter-false) {
        background-image: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMiIgaGVpZ2h0PSIxNiIgdmlld0JveD0iMCAwIDE0IDIwIj48cGF0aCBmaWxsPSIjZmZmIiBkPSJNMTQgMTNsLTIuNS0yLjVMNyAxNWwtNC41LTQuNUwwIDEzbDcgN3pNMTQgNy41TDExLjUgMTAgNyA1LjUgMi41IDEwIDAgNy41bDctN3oiLz48L3N2Zz4=)
    }

    .tablesorter-bootstrap thead.thead-dark .tablesorter-headerAsc, .tablesorter-bootstrap.table-dark thead .tablesorter-headerAsc {
        background-image: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMiIgaGVpZ2h0PSIxMiIgdmlld0JveD0iMCAwIDE0IDE0Ij48cGF0aCBmaWxsPSIjZmZmIiBkPSJNMTQgOS41TDExLjUgMTIgNyA3LjUgMi41IDEyIDAgOS41bDctN3oiLz48L3N2Zz4=)
    }

    .tablesorter-bootstrap thead.thead-dark .tablesorter-headerDesc, .tablesorter-bootstrap.table-dark thead .tablesorter-headerDesc {
        background-image: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMiIgaGVpZ2h0PSIxMiIgdmlld0JveD0iMCAwIDE0IDE0Ij48cGF0aCBmaWxsPSIjZmZmIiBkPSJNMTQgNWwtMi41LTIuNS00LjUgNC41LTQuNS00LjVMMCA1IDcgMTJ6Ii8+PC9zdmc+)
    }

    .tablesorter-bootstrap:not(.table-dark) > tbody > tr.odd > td, .tablesorter-bootstrap:not(.table-dark) > tbody > tr.tablesorter-hasChildRow.odd:hover ~ tr.tablesorter-hasChildRow.odd ~ .tablesorter-childRow.odd > td {
        background-color: #f9f9f9
    }

    .tablesorter-bootstrap:not(.table-dark) > tbody > tr.even:hover > td, .tablesorter-bootstrap:not(.table-dark) > tbody > tr.hover > td, .tablesorter-bootstrap:not(.table-dark) > tbody > tr.odd:hover > td, .tablesorter-bootstrap:not(.table-dark) > tbody > tr.tablesorter-hasChildRow.even:hover ~ .tablesorter-childRow.even > td, .tablesorter-bootstrap:not(.table-dark) > tbody > tr.tablesorter-hasChildRow.odd:hover ~ .tablesorter-childRow.odd > td {
        background-color: #f5f5f5
    }

    .tablesorter-bootstrap:not(.table-dark) > tbody > tr.even > td, .tablesorter-bootstrap:not(.table-dark) > tbody > tr.tablesorter-hasChildRow.even:hover ~ tr.tablesorter-hasChildRow.even ~ .tablesorter-childRow.even > td {
        background-color: #fff
    }

    .tablesorter-bootstrap .tablesorter-processing {
        background-image:    url(data:image/gif;base64,R0lGODlhFAAUAKEAAO7u7lpaWgAAAAAAACH/C05FVFNDQVBFMi4wAwEAAAAh+QQBCgACACwAAAAAFAAUAAACQZRvoIDtu1wLQUAlqKTVxqwhXIiBnDg6Y4eyx4lKW5XK7wrLeK3vbq8J2W4T4e1nMhpWrZCTt3xKZ8kgsggdJmUFACH5BAEKAAIALAcAAAALAAcAAAIUVB6ii7jajgCAuUmtovxtXnmdUAAAIfkEAQoAAgAsDQACAAcACwAAAhRUIpmHy/3gUVQAQO9NetuugCFWAAAh+QQBCgACACwNAAcABwALAAACE5QVcZjKbVo6ck2AF95m5/6BSwEAIfkEAQoAAgAsBwANAAsABwAAAhOUH3kr6QaAcSrGWe1VQl+mMUIBACH5BAEKAAIALAIADQALAAcAAAIUlICmh7ncTAgqijkruDiv7n2YUAAAIfkEAQoAAgAsAAAHAAcACwAAAhQUIGmHyedehIoqFXLKfPOAaZdWAAAh+QQFCgACACwAAAIABwALAAACFJQFcJiXb15zLYRl7cla8OtlGGgUADs=);
        background-position: center center !important;
        background-repeat:   no-repeat !important
    }

    .tablesorter-bootstrap:not(.table-dark) > tbody > tr.odd td.primary {
        background-color: #bfbfbf
    }

    .tablesorter-bootstrap:not(.table-dark) > tbody > tr td.primary, .tablesorter-bootstrap:not(.table-dark) > tbody > tr.even td.primary {
        background-color: #d9d9d9
    }

    .tablesorter-bootstrap:not(.table-dark) > tbody > tr.odd td.secondary {
        background-color: #d9d9d9
    }

    .tablesorter-bootstrap:not(.table-dark) > tbody > tr td.secondary, .tablesorter-bootstrap:not(.table-dark) > tbody > tr.even td.secondary {
        background-color: #e6e6e6
    }

    .tablesorter-bootstrap:not(.table-dark) > tbody > tr.odd td.tertiary {
        background-color: #e6e6e6
    }

    .tablesorter-bootstrap:not(.table-dark) > tbody > tr td.tertiary, .tablesorter-bootstrap:not(.table-dark) > tbody > tr.even td.tertiary {
        background-color: #f2f2f2
    }

    .tablesorter-bootstrap:not(.table-dark) > .caption {
        background-color: #fff
    }

    .tablesorter-bootstrap .tablesorter-filter-row input.tablesorter-filter, .tablesorter-bootstrap .tablesorter-filter-row select.tablesorter-filter {
        width:              98%;
        margin:             0;
        -webkit-box-sizing: border-box;
        -moz-box-sizing:    border-box;
        box-sizing:         border-box;
        -webkit-transition: height .1s ease;
        -moz-transition:    height .1s ease;
        -o-transition:      height .1s ease;
        transition:         height .1s ease
    }

    .tablesorter-bootstrap:not(.table-dark) .tablesorter-filter-row {
        background-color: #efefef
    }

    .tablesorter-bootstrap:not(.table-dark) .tablesorter-filter-row input.tablesorter-filter, .tablesorter-bootstrap:not(.table-dark) .tablesorter-filter-row select.tablesorter-filter {
        color: #333
    }

    .tablesorter-bootstrap .tablesorter-filter-row .tablesorter-filter.disabled {
        cursor:     not-allowed;
        box-shadow: 0 1px 1px rgba(0, 0, 0, .075) inset;
        box-sizing: border-box;
        transition: height .1s ease
    }

    .tablesorter-bootstrap:not(.table-dark) .tablesorter-filter-row td {
        line-height:        normal;
        text-align:         center;
        padding:            4px 6px;
        vertical-align:     middle;
        -webkit-transition: line-height .1s ease;
        -moz-transition:    line-height .1s ease;
        -o-transition:      line-height .1s ease;
        transition:         line-height .1s ease
    }

    .tablesorter-bootstrap .tablesorter-filter-row.hideme td {
        padding:     2px;
        margin:      0;
        line-height: 0
    }

    .tablesorter-bootstrap .tablesorter-filter-row.hideme * {
        height:     1px;
        min-height: 0;
        border:     0;
        padding:    0;
        margin:     0;
        opacity:    0
    }

    .tablesorter .filtered {
        display: none
    }

    .tablesorter-bootstrap .tablesorter-pager .pagedisplay {
        border: 0
    }

    .tablesorter:not(.table-dark) .tablesorter-errorRow td {
        text-align:       center;
        cursor:           pointer;
        background-color: #e6bf99
    }


    /* Cards    */

    .card {
        position: relative;
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-orient: vertical;
        -webkit-box-direction: normal;
        -ms-flex-direction: column;
        flex-direction: column;
        min-width: 0;
        word-wrap: break-word;
        background-color: #fff;
        background-clip: border-box;
        border: 1px solid rgba(0,0,0,.125);
        border-radius: .25rem;
    }
    .card-body {
        -webkit-box-flex: 1;
        -ms-flex: 1 1 auto;
        flex: 1 1 auto;
        padding: 1.25rem;
    }
    .card-title {
        margin-bottom: .75rem;
    }
    .card-header:first-child {
        border-radius: calc(.25rem - 1px) calc(.25rem - 1px) 0 0;
    }

    .card-header {
        padding: .75rem 1.25rem;
        margin-bottom: 0;
        background-color: rgba(0,0,0,.03);
        border-bottom: 1px solid rgba(0,0,0,.125);
    }
    .w-50 {
        width: 50%!important;
    }

    .table-responsive-sm{display:block;width:100%;overflow-x:auto;-webkit-overflow-scrolling:touch}.table-responsive-sm>.table-bordered{border:0}}@media (max-width:767.98px){.table-responsive-md{display:block;width:100%;overflow-x:auto;-webkit-overflow-scrolling:touch}.table-responsive-md>.table-bordered{border:0}}@media (max-width:991.98px){.table-responsive-lg{display:block;width:100%;overflow-x:auto;-webkit-overflow-scrolling:touch}.table-responsive-lg>.table-bordered{border:0}}@media (max-width:1199.98px){.table-responsive-xl{display:block;width:100%;overflow-x:auto;-webkit-overflow-scrolling:touch}.table-responsive-xl>.table-bordered{border:0}}.table-responsive{display:block;width:100%;overflow-x:auto;-webkit-overflow-scrolling:touch}.table-responsive>.table-bordered{border:0}
</style>


<?php

/**
 * @var $block \Elevate\PrintLabels\Block\Adminhtml\Index\Index
 */

$params = $block->getParams();

$max_orders_per_page = 90;

if (!isset($params['page'])) {
    $pagenumber = 1;
} else {
    $pagenumber = intval($params['page']);
}

if (!isset($params['date'])) {
    $date_set = false;
    $date_selected_to_view = false;

    $datepicker_value_set = $date_set;
    $datepicker_value = $date_selected_to_view;
    $order_data = $block->getOrdersByPage($pagenumber);
} else {
    $date_set = true;
    $date_selected_to_view = $params['date'];
    $datepicker_value_set = $date_set;
    $datepicker_value = $date_selected_to_view;
    $order_data = $block->getOrdersByDeliveryDate($pagenumber, $date_selected_to_view);
}

$orders = $order_data['order_data'];

//echo $this->getUrl();
//echo '<pre>';
//print_r($params);
//echo '</pre>';

$datepicker_placeholder = "Click to Select Date";

?>

<div class="printlabels-top-container">
    <div id="message-block"></div>


    <div id="info-toolbar">
        <div class="row">
        <div class="col-sm-4">
            <div id="datepicker-view" class="card">
                <div class="card-header">
                    <h4 id="datepicker-view-text" class="card-title">View Orders By Delivery Date</h4>
                </div>
                <div class="card-body">
                    <div id="datepicker-inputcontainer">
                        <?php
                        $input_output = 'placeholder="' . $datepicker_placeholder . '"';
                        if (!empty($datepicker_value_set)) {
                            $input_output .= ' value="' . $datepicker_value . '"';
                        }
                        ?>
                        <input type="text" id="thedatepicker" <?= $input_output ?>>
                        <i class="fa fa-calendar" style="margin-left:0.5rem;"></i>
                    </div>
                </div>
            </div>
        </div>
        <?php if (!empty($date_set)) { ?>
            <div class="col-sm-8">
                <a class="action-button" href="<?= $this->getUrl('printlabels/index/index') ?>">
                    <i class="fa fa-arrow-circle-left"></i> Return to All Orders
                </a>
            </div>
        <?php } ?>
        </div>
    </div>

    <div class="info-bar">
        <div class="btn btn-primary">
            Total Number of Orders <?php if (!empty($date_set)) { ?> for Selected Date <?php } ?><span class="badge badge-light"><?= $order_data['total_order_count'] ?></span>
        </div>
        <div class="btn btn-secondary">
            Number of Orders on Page <?php if (!empty($date_set)) { ?> for Selected Date <?php } ?><span class="badge badge-light"><?= $order_data['order_count'] ?></span>
        </div>

        <?php if ($order_data['alternative_orders_count']) { ?>
            <a type="button" class="btn btn-secondary" href="#alternative-orders-container">
                Alternative Dispatch Orders on Page <span class="badge badge-light"><?= $order_data['alternative_orders_count'] ?></span>
            </a>
        <?php } ?>
        <?php if ($order_data['problem_orders_count']) { ?>
            <a class="btn btn-danger" href="#problem-orders-container">
                Problem Orders on Page <span class="badge badge-dark"><?= $order_data['problem_orders_count'] ?></span>
            </a>
        <?php } ?>
    </div>
    <div id="actions-toolbar" class="actions-toolbar">

            <div class="d-inline-block">
                <?php if ($order_data['valid_order_count'] >= 1) { ?>
                    <div id="shipstuff" class="action-button"><i class="fa fa-print"></i> Ship Orders</div>
                <?php } ?>
            </div>
            <div class="d-inline-block">
                <?php if ($order_data['total_order_count'] > $max_orders_per_page) { ?>
                    <div class="pager-bar">
                        <ul class="items pages-items" aria-labelledby="paging-label">


                            <nav aria-label="...">
                                <ul class="pagination">

                                    <?php

                                    if ($pagenumber === 1) {
                                        $previous_item_class = 'disabled';
                                        $previous_item_link = '#';
                                        $previous_item_link_attribute = 'aria-disabled="true"';
                                    } else {
                                        $previous_item_class = '';
                                        $previous_item_link = $this->getTheUrl($pagenumber - 1);
                                        $previous_item_link_attribute = '';
                                    }

                                    ?>


                                    <li class="page-item <?= $previous_item_class; ?>">
                                        <a class="page-link" href="<?= $previous_item_link ?>" tabindex="-1" <?= $previous_item_link_attribute ?>>Previous</a>
                                    </li>
                                    <?php

                                    $pagenumber_max = ceil($order_data['total_order_count'] / $max_orders_per_page);
                                    $pagenumber_count = $pagenumber;

                                    for ($i = 1; $i <= $pagenumber_max; $i++) {
                                        $pagenumber_class = '';
                                        $active_attribute = '';
                                        $active_link_element = '';
                                        if ($i == $pagenumber) {
                                            $pagenumber_class = 'active';
                                            $active_attribute = 'aria-current="page"';
                                            $active_link_element = ' <span class="sr-only">(current)</span>';
                                        }

                                        echo '<li class="page-item ' . $pagenumber_class . '" ' . $active_attribute . '>';
                                        echo '<a class="page-link" href="' . $this->getTheUrl($i) . '">' . $i . ' ' . $active_link_element . '</a>';
                                        echo '</li>';
                                    }
                                    if ($pagenumber === $pagenumber_max) {
                                        $next_item_class = 'disabled';
                                        $next_item_link = '#';
                                        $next_item_link_attribute = 'aria-disabled="true"';
                                    } else {
                                        $next_item_class = '';
                                        $next_item_link = $this->getTheUrl($pagenumber + 1);
                                        $next_item_link_attribute = '';
                                    }

                                    ?>


                                    <li class="page-item <?= $next_item_class; ?>">
                                        <a class="page-link" href="<?= $next_item_link ?>" tabindex="-1" <?= $next_item_link_attribute ?>>Next</a>
                                    </li>

                                </ul>
                            </nav>
                        </ul>
                    </div>
                <?php } ?>
            </div>
    </div>
</div>



<div class="main-content">
    <div class="admin__data-grid-wrap">
        <form id="main-form">


            <?php if ($order_data['valid_order_count'] >= 1) { ?>
                <table class="tablesort-me tablesorter-bootstrap" data-role="grid">
                    <thead>
                    <tr>
                        <th class="data-grid-multicheck-cell" data-sorter="false"></th>
                        <th class="printlabels-th">
                            <span class="">ID</span>
                        </th>
                        <th class="printlabels-th">
                            <span class="">Purchase Date</span>
                        </th>
                        <th class="printlabels-th ">
                            <span class="">Delivery Date</span>
                        </th>
                        <th class="printlabels-th">
                            <span class="">Ship Name</span>
                        </th>
                        <th class="printlabels-th">
                            <span class="">Postcode</span>
                        </th>
                        <th class="printlabels-th orders-ship-tb-items">
                            <span class="">Items</span>
                        </th>
                        <th class="printlabels-th">
                            <span class="">Total</span>
                        </th>
                        <th class="printlabels-th">
                            <span class="">Gift Msg</span>
                        </th>
                        <th class="printlabels-th">
                            <span class="">Packages</span>
                        </th>
                        <th class="printlabels-th">
                            <span class="">Weight of Packages</span>
                        </th>
                        <th class="printlabels-th">
                            <span class="">Delivery Method</span>
                        </th>
                        <th class="data-grid-th" data-sorter="false">
                            <span class="">Action</span>
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php echo $order_data['html_output']; ?>
                    </tbody>
                </table>
            <?php } else { ?>
                <div class="no-orders">
                    <div class="message message-success success">You have shipped all shippable orders.</div>
                </div>
            <?php } ?>
        </form>
    </div>
</div>

<?php if ($order_data['alternative_orders_count'] >= 1) { ?>
    <div id="alternative-orders-container">
        <h3>Alternative Dispatch Orders</h3>
        <div class="problem-order-desc message message-error">
            These orders are for postcodes which have been specified are dispatched via an alternative method to your main courier.
        </div>
        <table class="tablesort-me tablesorter-bootstrap" data-role="grid">
            <thead>
            <tr>
                <!--
                <th class="data-grid-multicheck-cell">
                    <span class="">Include</span>
                </th>-->
                <th class="printlabels-th">
                    <span class="">ID</span>
                </th>
                <th class="printlabels-th ">
                    <span class="">Purchase Date</span>
                </th>
                <th class="printlabels-th ">
                    <span class="">Delivery Date</span>
                </th>
                <th class="printlabels-th">
                    <span class="">Ship Name</span>
                </th>
                <th class="printlabels-th">
                    <span class="">Postcode</span>
                </th>

                <th class="printlabels-th orders-ship-tb-items">
                    <span class="">Items</span>
                </th>
                <th class="printlabels-th">
                    <span class="">Total</span>
                </th>
                <th class="printlabels-th">
                    <span class="">Gift Message</span>
                </th>
                <th class="printlabels-th">
                    <span class="">No of Packages</span>
                </th>
                <th class="printlabels-th">
                    <span class="">Weight of Packages</span>
                </th>
                <th class="printlabels-th">
                    <span class="">Problem</span>
                </th>
                <th class="data-grid-th" data-sorter="false">
                    <span class="">Action</span>
                </th>
            </tr>
            </thead>
            <tbody>
            <?php echo $order_data['alternative_orders_html']; ?>
            </tbody>
        </table>

    </div>
<?php } ?>
<?php if ($order_data['problem_orders_count'] >= 1) { ?>
    <div id="problem-orders-container">
        <h3>Problem Orders</h3>
        <div class="problem-order-desc message message-error">
            These orders may have issues with the shipping address, and may require editing of the shipping address before they will be removed from this section upon page refresh.
        </div>
        <table class="tablesort-me tablesorter-bootstrap" data-role="grid">
            <thead>
            <tr>
                <!--
                <th class="data-grid-multicheck-cell">
                    <span class="">Include</span>
                </th>
                -->
                <th class="printlabels-th">
                    <span class="">ID</span>
                </th>
                <th class="printlabels-th ">
                    <span class="">Purchase Date</span>
                </th>
                <th class="printlabels-th ">
                    <span class="">Delivery Date</span>
                </th>
                <th class="printlabels-th">
                    <span class="">Ship Name</span>
                </th>
                <th class="printlabels-th">
                    <span class="">Postcode</span>
                </th>
                <th class="printlabels-th orders-ship-tb-items">
                    <span class="">Items</span>
                </th>
                <th class="printlabels-th">
                    <span class="">Total</span>
                </th>
                <th class="printlabels-th">
                    <span class="">Gift Message</span>
                </th>
                <th class="printlabels-th">
                    <span class="">Packages</span>
                </th>
                <th class="printlabels-th">
                    <span class="">Weight of Packages</span>
                </th>
                <th class="printlabels-th">
                    <span class="">Problem</span>
                </th>
                <th class="data-grid-th" data-sorter="false">
                    <span class="">Action</span>
                </th>
            </tr>
            </thead>
            <tbody>
            <?php echo $order_data['problem_orders_html']; ?>
            </tbody>
        </table>

    </div>
<?php } ?>
<div id="ajaxResponse"></div>

<div id="loading-overlay" class="loading">
    <div class="loader"></div>
    <div class="loader-message">Attempting to ship orders...</div>
</div>
<script type="text/javascript">
    require(["jquery", "jquery/ui", 'tablesorter'], function ($) {

        var admin_url = '<?= $block->getAdminUrl(); ?>';


        jQuery('#select-date').click(function(){
            jQuery("#thedatepicker").datepicker('show');
        });

        jQuery('#thedatepicker').datepicker({
            dateFormat: "yy-mm-dd",
            onSelect: function(value, date) {
                jQuery('#thedatepicker').val(value);
                jQuery('#datepicker').hide();
                window.location = admin_url + 'date/' + value;
            }
        });



        jQuery('#shipstuff').on('click touchend', (function () {



            jQuery('#message-block').html('');
            jQuery('.loading').show();
            var ajaxRequest;

            // collect data from table

            // Find Checked Rows

            var checked_orders = jQuery('#main-form').find('.include-row:checked');


            var order_ids = [];


            var excluded_order_ids = [];
            var included_order_ids = [];

            var order_ids = [];
            var data_to_send = {};

            jQuery(checked_orders).each(function () {
                //console.log(jQuery(this).val());
                order_ids.push(jQuery(this).attr('data-row-id'));
            });

            if (order_ids === undefined || order_ids.length == 0) {
                // No Orders
                jQuery('#message-block').append('<div data-order_id="' + order_id + '" class="message message-error error" >' + main_message + ' - ' + order_id + '</div>');
            }


            jQuery.each(order_ids, function (key, value) {

                var data_elements = jQuery('[data-row-id="' + value + '"]');


                jQuery(data_elements).each(function (index, value1) {

                    var temp_object = {};

                    if (jQuery(this).is('input')) {
                        // Only the checkbox atm - so ignore
                    } else if (jQuery(this).is('select')) {
                        // Get the Values on each for Qty of packages and Method Selected

                        var element_name = jQuery(this).attr('name');
                        var element_val = jQuery(this).val();
                        temp_object[element_name] = element_val;

                    }

                    if (typeof data_to_send[value] !== 'undefined') {
                        data_to_send[value].push(temp_object);
                    } else {
                        data_to_send[value] = [temp_object];
                    }


                });
            });


            console.log(data_to_send);


            var formdata = jQuery('#main-form').serialize();
            //console.log(formdata);
            var arraydata = jQuery('#main-form').serializeArray();
            //console.log(arraydata);

            var data_to_send_json = JSON.stringify(data_to_send);
            //console.log(data_to_send_json);

            ajaxRequest = jQuery.ajax({
                url: "<?php echo $this->getUrl('printlabels/test/test'); ?>?isAjax=true",
                type: 'POST',
                data: {
                    form_key: window.FORM_KEY,
                    formdata: arraydata,
                    data_to_send: data_to_send_json,
                    datasend: data_to_send
                },
                dataType: 'json',
                beforeSend: function () {
                    jQuery('#loader').show();
                },
                success: function (response) {

                    jQuery('.loading').hide();
                    jQuery("#ajaxResponse").html(response);
                    console.log(response);
                    $("#page_order_state").val(response["data"]);
                    const keys = Object.keys(response);
                    const something = Object.values(response);
                    const more = Object.entries(response);

                    // How To Handle Partial Successes etc

                    for (const somethin of something) {
                        var order_id = somethin.order_id;
                        var overall_success = parseInt(somethin.success);
                        var main_message = somethin.main_message;
                        var no_data = somethin.no_data;

                        if (no_data === 1) {
                            jQuery('#message-block').append('<div class="message message-error error" >' + main_message + '</div>');
                            break;
                        }

                        if (overall_success === 1) {
                            // Success
                            jQuery('#message-block').append('<div data-order_id="' + order_id + '" class="message message-success success" >' + main_message + ' - ' + order_id + '</div>');
                            // Remove Order From List
                            jQuery('tr[data-order-id=' + order_id + ']').remove();
                        } else {
                            // Fail ?
                            jQuery('#message-block').append('<div data-order_id="' + order_id + '" class="message message-error error" >' + main_message + ' - ' + order_id + '</div>');
                        }

                    }
                },
                error: function (xhr, status, errorThrown) {
                    jQuery('.loading').hide();
                    console.log(status);
                    console.log(xhr);
                    console.log(errorThrown);
                }
            });
        }));


        jQuery('.data-row').on('click touchend', (function (event) {
            var rowinput = jQuery(this).find('td div input.include-row');
            console.log(rowinput);

            // Don't Want it to Do the Click Magic on 3 things
            if (jQuery(event.target).hasClass('number_of_packages_select') || jQuery(event.target).hasClass('shipping_methods') || jQuery(event.target).hasClass('view-order-data')) {

            } else {
                if (jQuery(this).hasClass('included')) {
                    jQuery(this).removeClass('included');
                    jQuery(rowinput).prop('checked', 0);
                } else {

                    jQuery(rowinput).prop('checked', 1);
                    jQuery(this).addClass('included');
                }
            }


        }));


        function getOrders() {
            // Get Orders for Main Bit of Page
            var ajaxRequest;
            ajaxRequest = jQuery.ajax({
                url: "<?php echo $this->getUrl('printlabels/orders/getorders'); ?>?isAjax=true",
                type: 'POST',
                data: {
                    form_key: window.FORM_KEY,
                    formdata: arraydata
                },
                dataType: 'json',
                beforeSend: function () {
                    jQuery('#loader').show();
                },
                success: function (response) {
                    jQuery("#ajaxResponse").html(response);
                    console.log(response);
                    $("#page_order_state").val(response["data"]);
                    const keys = Object.keys(response);
                    const something = Object.values(response);
                    const more = Object.entries(response);

                    for (const somethin of something) {
                        var order_id = somethin.order_id;
                        var success = parseInt(somethin.success);

                        if (success === 1) {
                            // Success
                            jQuery('#message-block').append('<div data-order_id="' + order_id + '" class="message message-success success" >Order Success - ' + order_id + '</div>');
                        } else {
                            // Fail ?
                            jQuery('#message-block').append('<div data-order_id="' + order_id + '" class="message message-error error" >Couldn\'t Ship Order  - ' + order_id + '</div>');
                        }

                        console.log(somethin.success);
                        console.log(somethin.order_id);
                        console.log(somethin);
                    }
                },
                error: function (xhr, status, errorThrown) {
                    console.log(status);
                    console.log(xhr);
                    console.log(errorThrown);
                }
            });
        }

        jQuery('.view-order-data').on('click touchend', (function () {

            var other_stuff = jQuery('#modal-content > div').detach();
            jQuery('#order_data_hidden').append(other_stuff);

            var order_id = jQuery(this).attr('data-order-id');
            var order_info = jQuery('#order_data_hidden').find('#order_' + order_id).detach();
            jQuery('#modal-content').append(order_info);
        }));


        jQuery('#checkview').on('click touchend', (function () {
            console.log(this);
            console.log(jQuery(this).attr('data-order-id'));
            // Get Orders for Main Bit of Page
            var ajaxRequest;

            var order_id = jQuery(this).attr('data-order-id');

            ajaxRequest = jQuery.ajax({
                url: "<?php echo $this->getUrl('printlabels/order/viewer'); ?>?isAjax=true",
                type: 'POST',
                data: {
                    form_key: window.FORM_KEY,
                    order_id: order_id
                },
                dataType: 'html',
                beforeSend: function () {
                    jQuery('#loader').show();
                },
                success: function (response) {
                    jQuery("#ajaxResponse").html(response);
                    console.log(response);
                    jQuery("#modal-content").html(response);
                },
                error: function (xhr, status, errorThrown) {
                    console.log(status);
                    console.log(xhr);
                    console.log(errorThrown);
                }
            });
            console.log(ajaxRequest);
        }));

        function getOrderData() {


        }

        jQuery(document).ready(function () {


            jQuery('.shipping_methods').find('.hide-me').hide();

            var shipping_methods = jQuery('.shipping_methods');


            jQuery('.tablesort-me').tablesorter({theme: "bootstrap"});


            jQuery(shipping_methods).each(function (index, element) {

                // Selects Most Likely Best Option?

                var best_option = jQuery(element).find('option[data-networkcode="2^32"]');

                //jQuery(best_option).prop('selected',true);
            });
        });

    });
</script>
<div id="order_data_hidden">
    <?php
    foreach ($orders as $key => $value) { ?>
        <div id="order_<?php echo $key; ?>" class="order_<?php echo $key; ?>"><?php echo $value; ?></div>
    <?php }

    ?>
</div>

<div data-bind="mageInit: {
        'Magento_Ui/js/modal/modal':{
            'type': 'popup',
            'title': 'Order Details',
            'trigger': '[data-trigger=trigger]',
            'responsive': true,
            'buttons': [{
                text: 'Close',
                class: 'action'
            }]
        }}">
    <div id="modal-content" class="content">

    </div>


</div>
