<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for displaying products list widget
 *
 * @var $block \Magento\CatalogWidget\Block\Product\ProductsList
 */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
    <?php
    $_helperCategoryName = $this->helper('SkyPremium\Catalog\Helper\GetNameOfCategory');
    $_helperCategory = $this->helper('SkyPremium\Catalog\Helper\Data');
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $title = $block->getTitle() ? __($block->getTitle()) : '';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;

    //processing these items that already in wishlist of customer
    $_helperWishList           = $this->helper('Magento\Wishlist\Helper\Data');
    $_helperWishListSkyPremium = $this->helper('SkyPremium\Wishlist\Helper\Data');
    $_helperAmasty = $this->helper('Amasty\Groupcat\Helper\Data');
    $_wishListCollection       = $_helperWishList->getWishlistItemCollection();
    $_itemsWishList            = $_wishListCollection->getItems();
    $_itemsWishList                  = $_helperWishListSkyPremium->resetItemWishlistByProducts($_itemsWishList);
    $_categoriesNotAllowShowWishlist = $_helperCategoryName->getCategoriesNotAllowShowWishList();
    
    
    $customerRule  = $_helperAmasty->getRulesCustomerBySession();

    ?>
    <div class="block widget block-products-list <?php /* @escapeNotVerified */
    echo $mode; ?>">
        <section class="slider">
            <?php if ($title): ?>
                <div class="block-title">
                    <h1><?php /* @escapeNotVerified */
                        echo $title; ?></h1>
                </div>
            <?php endif ?>
            <div class="block-content">
                <?php /* @escapeNotVerified */
                echo '<!-- ' . $image . '-->' ?>
                <div class="products products-<?php /* @escapeNotVerified */
                echo $mode; ?> <?php /* @escapeNotVerified */
                echo $mode; ?>">
                    <div id="recommended-privileges" class="product-items <?php /* @escapeNotVerified */
                    echo $type; ?>  owl-carousel owl-theme">
                        <?php $iterator = 1; ?>
                        <?php foreach ($items as $_item): ?>
                            <?php /* @escapeNotVerified */
                            echo ($iterator++ == 1) ? '<div class="product-item">' : '</div><div class="product-item">' ?>
                            <input type="hidden" value="<?php echo $_item->getId(); ?>">
                            <div class="product-item-info">
                                <a href="<?php /* @escapeNotVerified */
                                echo $block->getProductUrl($_item) ?>" class="product-item-photo">
                                    <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                                </a>
                                <div class="product-item-details product details product-item-details-container">
                                    <div class="time-sale">
                                    <?php $dealDetail = $_helperCategory->getTimeSaleItem($_item);
                                    if ($dealDetail && $dealDetail['deal_status'] && isset($dealDetail['diff_timestamp'])):
                                        $saveBoxAvl     = isset($dealDetail['saved-amount']) ? '' : 'notavilable';
                                        ?>
                                        <div class="deal wk-daily-deal" data-deal-id="<?php echo $_item->getId();?>" data-update-url="<?php echo $dealDetail['update_url'];?>">
                                            <p class="wk_cat_count_clock<?php echo $saveBoxAvl?>" data-stoptime="<?php echo $dealDetail['stoptime'];?>" data-diff-timestamp ="<?php echo $dealDetail['diff_timestamp'];?>"></p>
                                        </div>
                                        <?php
                                    endif;
                                    ?>
                                    </div>
                                    <div class="product product-item-new-row">
                                        <?php if ($_helperCategory->showProductAsNew($_item)):?>
                                            <div class="product product-item-new-block">
                                                <span><?php echo __('NEW'); ?></span>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                    <div class="product-item-favourite-row">
                                        <div class="actions-secondary" data-role="add-to-links">
                                            <?php
                                            if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist):
                                                $itemWishlist = $_helperWishListSkyPremium->checkingProductIsAddedToWishList($_itemsWishList, $_item);
                                                $allowShowWishList = $_helperCategoryName->checkingCategoryAllowShowWishlist($_item, $_categoriesNotAllowShowWishlist);
                                                
                                                
                                                if($allowShowWishList):
                                                    if ($_helperAmasty->checkFavoriteItems($_item->getId()) == false ):
                                                        ?>
                                                        <a href="#"
                                                           data-post='<?php /* @escapeNotVerified */
                                                           echo $block->getAddToWishlistParams($_item); ?>'
                                                           class="action towishlist" data-action="add-to-wishlist"
                                                           title="<?php /* @escapeNotVerified */
                                                           echo __('Add to Wish List') ?>">
                                                            <span><?php /* @escapeNotVerified */
                                                                echo __('Add to Wish List') ?></span>
                                                        </a>
                                                    <?php else: ?>
                                                        <a href="#" data-role="remove"
                                                           data-post='<?php /* @escapeNotVerified */
                                                           echo $_helperWishList->getRemoveParams($itemWishlist); ?>'
                                                           title="<?php /* @escapeNotVerified */
                                                           echo __('Remove Favourite') ?>" class="btn-remove action delete">
                                                            <span><?php /* @escapeNotVerified */
                                                                echo __('Remove Favourite'); ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                <?php endif;?>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                    <div class="product product-item-sub-category-row">
                                        <?php /* @escapeNotVerified */ echo $_helperCategoryName->getNameRootCategory($_item); ?>
                                    </div>
                                    <div class="product product-item-name-row">
                                        <strong class="product-item-name">
                                            <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                               href="<?php /* @escapeNotVerified */
                                               echo $block->getProductUrl($_item) ?>"
                                               class="product-item-link">
                                                <?php echo $block->escapeHtml($_item->getName()) ?>
                                            </a>
                                        </strong>
                                    </div>
                                    <div class="product product-item-partner-row">
                                        <span><?php /* @escapeNotVerified */ echo $_helperCategoryName->getNameCategoryNeedFilter($_item); ?></span>
                                    </div>
                                     
                                    <?php
                                        $arr_rule = $_helperAmasty->getAllMemberShipAndServiceBagsProduct($_item);
                                        if (!empty($arr_rule)):
                                        
                                    ?>
                                    <div class="product product-service-exclusivity-row">
                                        <?php 
                                            foreach ($arr_rule as $valueRuleProduct):
                                            $serviceIcon = "";
                                            if($valueRuleProduct) {
                                                if ($valueRuleProduct == "PLATINUM"){
                                                    $serviceIcon = "images/Platinum1x.png";
                                                }else if ($valueRuleProduct == "PLEASURE"){
                                                    $serviceIcon = "images/Pleasures1x.png";
                                                }else if ($valueRuleProduct == "THE MULTIPLAY"){
                                                    $serviceIcon = "images/MultiPlay1x.png";
                                                }
                                            }
    
                                            if($serviceIcon != "") {
                                        ?>
                                        <img src="<?php echo $block->getViewFileUrl($serviceIcon)?>" alt="">
                                    
                                        <?php } ?>
                                        <?php endforeach;?>
                                    </div>
                                    <?php endif;?>
                                
                                </div>
                                <div class="product product-item-inner product-item-actions-container">
                                    <?php
                                    $showAddToCart = $_helperCategory->showAddToCart($_item);
                                    $product_button_type = $_helperCategory->checkButtonType($_item);
                                    $add_to_cart_class = '';
                                    if ($product_button_type != 'in_stock') {
                                        $add_to_cart_class = 'not-sale-product';
                                    } ?>
                                    <div class="product actions product-item-actions <?php echo $add_to_cart_class; ?>">
                                        <?php if ($templateType): ?>
                                            <?php //echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                        <?php endif; ?>

                                        <?php if ($showAddToCart) { ?>
                                            <div class="actions-primary">

                                                <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                    <?php if ($product_button_type == 'in_stock') { ?>
                                                        <button class="action tocart primary"
                                                                data-mage-init='{"redirectUrl": {"url": "<?= /* @escapeNotVerified */
                                                                $block->getAddToCartUrl($_item) ?>"}}' type="button"
                                                                title="<?= /* @escapeNotVerified */
                                                                __('Add to Cart') ?>">
                                                                <span><?= /* @escapeNotVerified */
                                                                    __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php } else { ?>
                                                        <?php if ($product_button_type == 'sold_out') {
                                                            $buttonTitle = __('Sold Out');
                                                        } ?>
                                                        <?php if ($product_button_type == 'sale_not_started') {
                                                            $buttonTitle = __('Sale Not Started');
                                                        } ?>
                                                        <?php if ($product_button_type == 'sales_over') {
                                                            $buttonTitle = __('Sales Over');
                                                        } ?>

                                                        <?php if ($product_button_type == 'in_cart') {
                                                            $buttonTitle = __('In Cart');
                                                        } ?>
                                                        <button type="button"
                                                                title="<?php echo $block->escapeHtml($buttonTitle); ?>"
                                                                class="action tocart primary disabled not-sale">
                                                    <span><?php /* @escapeNotVerified */
                                                        echo $buttonTitle; ?></span>
                                                        </button>
                                                    <?php } ?>


                                                <?php else: ?>
                                                    <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                    $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                    ?>

                                                    <?php if ($product_button_type == 'in_stock') { ?>
                                                        <button class="action tocart primary"
                                                                data-post='<?= /* @escapeNotVerified */
                                                                $postData ?>'
                                                                type="button" title="<?= /* @escapeNotVerified */
                                                        __('Add to Cart') ?>">
                                                                <span><?= /* @escapeNotVerified */
                                                                    __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php } else { ?>
                                                        <?php if ($product_button_type == 'sold_out') {
                                                            $buttonTitle = __('Sold Out');
                                                        } ?>
                                                        <?php if ($product_button_type == 'sale_not_started') {
                                                            $buttonTitle = __('Sale Not Started');
                                                        } ?>
                                                        <?php if ($product_button_type == 'sales_over') {
                                                            $buttonTitle = __('Sales Over');
                                                        } ?>

                                                        <?php if ($product_button_type == 'in_cart') {
                                                            $buttonTitle = __('In Cart');
                                                        } ?>
                                                        <button type="button"
                                                                title="<?php echo $block->escapeHtml($buttonTitle); ?>"
                                                                class="action tocart primary disabled not-sale">
                                                    <span><?php /* @escapeNotVerified */
                                                        echo $buttonTitle; ?></span>
                                                        </button>
                                                    <?php } ?>


                                                <?php endif; ?>
                                            </div>
                                        <?php } else { ?>
                                            <!-- custom code for view detail (noted: deleted useless Magento default for add to cart, wishlist)
                                        check the original file if want to revert it -->
                                            <div class="actions-primary view-detail">
                                                <a href="<?php /* @escapeNotVerified */
                                                echo $block->getProductUrl($_item) ?>" class="action tocart primary">
                                                    <?php /* @escapeNotVerified */
                                                    echo __('View details'); ?>
                                                </a>
                                            </div>
                                        <?php } ?>


                                    </div>
                                </div>
                            </div>
                            <?php echo ($iterator == count($items) + 1) ? '</div>' : '' ?>
                        <?php endforeach ?>
                    </div>
                </div>
                <?php echo $block->getPagerHtml() ?>
            </div>
        </section>
    </div>
<?php endif; ?>
<?php 
    $this->setCacheKey(uniqid());
?>
<script type="text/x-magento-init">
    {
        "body": {
             "viewondeal": {}
        }
    }
</script>