<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @see \Magento\Sales\Block\Adminhtml\Items\Column\Name
 */
?>
<tr><td colspan="4"><?php echo $this->test(); ?></td></tr>
<?php /* if ($_item = $block->getItem()): ?>
        <tr><td colspan="3"><?php echo $block->escapeHtml($_item->getAdditionalData()) ?></td></tr>
<?php endif; */ ?>
