<?php
/** @var \SecureTrading\Trust\Block\Adminhtml\PaymentPage\Form $block */

$code = $block->escapeHtml($block->getMethodCode());
$ccType = $block->getInfoData('cc_type');
$ccExpYear = $block->getInfoData('cc_exp_year');
$ccExpMonth = $block->getInfoData('cc_exp_month');

?>
<fieldset class="admin__fieldset payment-method"
    <?= isset($secureRenderer) ? '' : 'style= "display: none;"' ?>
          id="payment_form_<?= /* @noEscape */ $code ?>"
>
    <div class="admin__field _required">
        <label class="label admin__field-label" for="<?= /* @noEscape */ $code ?>_cc_type" >
            <span><?= $block->escapeHtml(__('Credit Card Type')) ?></span>
        </label>
        <div class="admin__field-control control">
            <select id="<?= /* @noEscape */ $code ?>_cc_type" name="payment[cc_type]"
                    class="required-entry select admin__control-select validate-cc-type-select">
				<?php foreach ($block->getCcAvailableTypes() as $typeCode => $typeName) : ?>
                    <option value="<?= $block->escapeHtml($typeCode) ?>"
						<?php if ($typeCode == $ccType) : ?> selected="selected"<?php endif; ?>>
						<?= $block->escapeHtml($typeName) ?>
                    </option>
				<?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="field-number admin__field _required">
        <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>_cc_number">
            <span><?= $block->escapeHtml(__('Credit Card Number')) ?></span>
        </label>
        <div class="admin__field-control">
            <input type="text" id="<?= /* @noEscape */ $code ?>_cc_number" name="payment[cc_number]"
                   title="<?= $block->escapeHtml(__('Credit Card Number')) ?>" class="admin__control-text validate-cc-number"
                   value="<?= /* @noEscape */ $block->getInfoData('cc_number') ?>"/>
        </div>
    </div>
    <div class="field-date admin__field _required">
        <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>_cc_exp_month">
            <span><?= $block->escapeHtml(__('Expiration Date')) ?></span>
        </label>
        <div class="admin__field-control control">
            <select id="<?= /* @noEscape */ $code ?>_cc_exp_month" name="payment[cc_exp_month]"
                    class="admin__control-select admin__control-select-month validate-cc-exp required-entry">
				<?php foreach ($block->getMonths() as $k => $v) : ?>
                    <option value="<?= $block->escapeHtml($k) ?>"
					        <?php if ($k == $ccExpMonth) : ?>selected="selected"<?php endif ?>>
						<?= $block->escapeHtml($v) ?>
                    </option>
				<?php endforeach; ?>
            </select>
            <br>
            <select id="<?= /* @noEscape */ $code ?>_cc_exp_year" name="payment[cc_exp_year]"
                <?= isset($secureRenderer) ? '' : 'style= ""margin-top: 25px;"' ?>
                    class="admin__control-select admin__control-select-year required-entry">
				<?php foreach ($block->getYears() as $k => $v) : ?>
                    <option value="<?= /* @noEscape */ $k ? $block->escapeHtml($k) : '' ?>"
					        <?php if ($k == $ccExpYear) : ?>selected="selected"<?php endif ?>>
						<?= $block->escapeHtml($v) ?>
                    </option>
				<?php endforeach ?>
            </select>
        </div>
    </div>
	<?php if ($block->hasVerification()) : ?>
        <div class="admin__field _required field-cvv" id="<?= /* @noEscape */ $code ?>_cc_type_cvv_div">
            <label for="<?= /* @noEscape */ $code ?>_cc_cid" class="admin__field-label">
                <span><?= $block->escapeHtml(__('Card Verification Number')) ?></span>
            </label>

            <div class="admin__field-control">
                <input type="text" title="<?= $block->escapeHtml(__('Card Verification Number')) ?>"
                       data-container="<?= /* @noEscape */ $code ?>-cc-cvv"
                       class="admin__control-text cvv"
                       id="<?= /* @noEscape */ $code ?>_cc_cid" name="payment[cc_cid]"
                       value=""
                       data-validate='{"required-number":true, "validate-cc-cvn":"#<?= /* @noEscape */ $code ?>_cc_type"}'
                       autocomplete="off"/>
            </div>
        </div>
	<?php endif; ?>

    <input type="hidden" id="<?= /* @noEscape */ $code ?>_payment_method_nonce" value="<?= $block->getPaymentAction() ?>"
           name="payment[payment_action]"/>
</fieldset>

<?= isset($secureRenderer) ? $secureRenderer->renderStyleAsTag("display: none;", '#payment_form_'.$code) : '' ?>
<?= isset($secureRenderer) ? $secureRenderer->renderStyleAsTag("margin-top: 25px;", '#'.$code.'_cc_exp_year') : '' ?>
