<?php

$shippingObject = $this->getDpdAuthorisation();
$helper = $this->getHelper();
$order = $block->getOrder();

$shipping_address = $order->getShippingAddress();

$shipping_firstname = $order->getShippingAddress()->getFirstname();
$shipping_lastname = $order->getShippingAddress()->getLastname();
$shipping_customer_name = $shipping_firstname . ' ' . $shipping_lastname;
$shipping_telephone_tmp = $order->getShippingAddress()->getTelephone();
$shipping_customer_email = $order->getShippingAddress()->getEmail();
$shipping_postcode = $order->getShippingAddress()->getPostcode();
$shipping_city = $order->getShippingAddress()->getCity();
$shipping_region = $order->getShippingAddress()->getRegion();
$shipping_address_tmp = $order->getShippingAddress()->getData('street');
$shipping_company = $order->getShippingAddress()->getCompany();
$shipping_country_code = $order->getShippingAddress()->getCountryId(); //2 letter iso - e.g US

$shipping_weight = $order->getWeight();
// Init

//lets check this is a valid package type we can use    

// The shipmentType variable can be set to 1 or 2 if a collection on delivery or swap it service is required. The deliveryDirection flag should be set to 1 for outbound and 2 for inbound shipments.

$dataArray = array(
    'collectionDetails' => [
        'address' => [
            'locality'    => $helper->getSenderOrgStreet2(),
            'county'      => $helper->getSenderOrgCounty(),
            'postcode'    => $helper->getSenderOrgPostcode(),
            'countryCode' => $helper->getSenderOrgCountryCode()
        ],
    ],
    'deliveryDetails'   => [
        'address' => [
            'locality'    => '',
            'county'      => $shipping_region,
            'postcode'    => $shipping_postcode,
            'countryCode' => $shipping_country_code
        ],
    ],
    'deliveryDirection' => 1,
    'numberOfParcels'   => 1,
    'totalWeight'       => $shipping_weight,
    'shipmentType'      => 0
);

//gets the available services
$shipping_array = $shippingObject->getShipping($dataArray);

?>

<div id="shipping_form">
  <p>Print a DPD Shipping Label</p>
  <input type="hidden" name="order_id" value="<?php echo $block->getOrderId() ?>"/>
  <input type="hidden" name="increment_id" value="<?php echo $order->getIncrementId() ?>"/>
  <style>
    #shipping_table {
      width: 50%;
    }

    #shipping_table input, #shipping_table select {
      width: 100%;
    }

    #shipping_table td {
      padding: 5px 7px;
    }

    #shipping_table tr {
      border: 1px solid;
    }

    table tr:nth-child(odd) td {
      background-color: #f0f0f0;
    }

    table tr:nth-child(even) td {
    }
  </style>

  <table id="shipping_table">

    <tr>
      <td>Email</td>
      <td><input type="text" name="email" value="<?php echo $order->getCustomerEmail(); ?>"/></td>
    </tr>
    <tr>
      <td>Name</td>
      <td><input type="text" name="shipping_contactName" value="<?php echo $shipping_customer_name; ?>"/></td>
    </tr>
    <tr>
      <td>Tel</td>
      <td><input type="text" name="shipping_telephone" value="<?php echo $shipping_telephone_tmp; ?>"/></td>
    </tr>
    <tr>
      <td>Org</td>
      <td><input type="text" name="shipping_address_organisation" value="<?php echo $shipping_company; ?>"/></td>
    </tr>
    <tr>
      <td>Country Code</td>
      <td><input type="text" name="shipping_address_countryCode" value="<?php echo $shipping_country_code; ?>"/></td>
    </tr>
    <tr>
      <td>Post Code</td>
      <td><input type="text" name="shipping_address_postcode" value="<?php echo $shipping_postcode; ?>"/></td>
    </tr>
    <tr>
      <td>Street</td>
      <td><input type="text" name="shipping_address_street" value="<?php echo $shipping_address_tmp; ?>"/></td>
    </tr>
    <tr>
      <td>Locality</td>
      <td><input type="text" name="shipping_address_locality" value=""/></td>
    </tr>
    <tr>
      <td>Town</td>
      <td><input type="text" name="shipping_address_town" value="<?php echo $shipping_city; ?>"/></td>
    </tr>
    <tr>
      <td>County</td>
      <td><input type="text" name="shipping_address_county" value="<?php echo $shipping_region; ?>"/></td>
    </tr>
    <tr>
      <td>Network Code</td>
      <td><select name="shipping_networkCode">
            <?php echo $helper->getShippingOptionsSelect($shipping_array, $order); ?>
        </select></td>
    </tr>
    <tr>
      <td>Number of Parcels</td>
      <td><input type="text" name="shipping_numberOfParcels" value="1"/></td>
    </tr>
    <tr>
      <td>Weight</td>
      <td><input type="text" name="shipping_totalWeight" value="5"/></td>
    </tr>
    <tr>
      <td>Delivery Instructions</td>
      <td><input type="text" name="shipping_deliveryInstructions" value=""/></td>
    </tr>
  </table>

  <button id="evPrintLabels">Print Label</button>


</div>
<div id="shipping_response"></div>

<script type="text/x-magento-init">
    {
        "*": {
            "elevatePrintLabels": {"postUrl":"<?php echo $block->getAdminPostUrl() ?>"}
        }
    }

</script>