<?php
    /** @var \SecureTrading\Trust\Block\Adminhtml\PaymentPage\Raw $block */

?>
<form action="<?php print $block->getRedirectUrl(); ?>" method="post" id="securetrading_stpp_redirect_form">
    <input type="hidden" name="_charset_"/>
    <?php $orderData = $block->getOrderData()?>
    <?php foreach ($orderData['info'] as $k => $v): ?>
		<?php if (is_array($v)): ?>
			<?php foreach ($v as $value): ?>
                <input type="hidden" name="<?php print $k; ?>"
                       value="<?= $block->escapeHtml($value); ?>"/>
			<?php endforeach; ?>
        <?php else: ?>
            <input type="hidden" name="<?php print $k; ?>"
                   value="<?= $block->escapeHtml($v); ?>"/>
        <?php endif; ?>
    <?php endforeach; ?>
    <input type="submit" value="Pay"/>
</form>
<?php $scriptString = <<<script
     document.body.onload = function () {
        document.getElementById("securetrading_stpp_redirect_form").submit();
    };
script;
?>

<?=  isset($secureRenderer) ? $secureRenderer->renderTag('script', [], $scriptString, false) : '<script>'.$scriptString.'</script>' ?>

<noscript>
    <p>You are seeing this message because JavaScript is disabled. Click "Pay" to continue with your transaction.</p>
</noscript>