<?php
    /** @var \Punchout2go\Punchout\Block\Transfer $this */

    /** @var $cartObj \Punchout2go\Punchout\Cart */
    $cartObj = $this->getPunchoutCart();
    /** @ var \Punchout2go\Punchout\Model\Session $punchoutSession */
    $punchoutSessionId = $cartObj->getPunchoutSessionId();
    $punchoutReturnUrl = $cartObj->getPunchoutReturnUrl();
    /** @var \Magento\Checkout\Model\Cart $mageCart */
    $mageCart = $this->getMageCart();
    $quote = $mageCart->getQuote();


?>
<script src="https://connect.punchout2go.com/jslib/0.0.1/po2go_mage.js?r=1.1" type="text/javascript"></script>
<script>
    // initiate the object and set the session id.
    jQuery(function() {
        POSession = new Po2go({
            'account': "<?php echo $this->getHelper()->getConfig('punchout2go_punchout/system/api_key'); ?>",
            'session_id':"<?php echo $punchoutSessionId; ?>",
            'return_url':"<?php echo $punchoutReturnUrl; ?>"
        });
        POSession.init();
    });
</script>
<!-- cart totals -->
<script type="text/javascript">
    jQuery(function () {
        // enable "edit" mode so people can use cXML edit function
        POSession.cart.edit_mode = 1;

        // add the "totals". the "total" is the only required
        // value. everything else can be empty or excluded.

        <?php
        $cartData = $cartObj->getData();

        foreach ($cartData AS $key=>$value) {
            echo "\t\tPOSession.cart.{$key} = ";
            if (is_array($value)) {
                echo json_encode($value) .";\n";
            } else {
                echo "\"{$value}\";\n"; 
            }
            
        }
        ?>

    });
</script>
<!-- loop through your items and add each to the object -->
<?php
/**
 * @var  $k
 * @var \Punchout2go\Punchout\Cart\Item $item
 */
foreach ($cartObj->getItems() AS $k => $item) { ?>
    <script>
        jQuery(function() {
            POSession.addItemToCart(<?php echo $item->toJson(); ?>);
        });
    </script>
<?php } ?>

<table cellspacing="0" cellpadding="0" border="0" width="100%" height="80%">
    <tr>
        <td align="center" valign="middle">
            <?php if ($this->getHelper()->getConfig('punchout2go_punchout/system/debug_transfer')) { ?>
                <a href="javascript:POSession.transferCart()">Transfer</a>
                <!-- with everything set, the last thing to do is send it -->
                <script>
                    jQuery(function () {
                        // just call the transfer function, no click required.
                        POSession.debug();
                    });
                </script>
            <?php } else { ?>
                <script>
                    jQuery(function () {
                        jQuery.cookie('section_data_ids','{}');
                        POSession.transferCart();
                    });
                </script>
            <?php } ?>
            <br>
        </td>
    </tr>
</table>

<script>
    localStorage.clear();
</script>
<script>
    sessionStorage.clear();
</script>
